version: '3'

services:
  logstash:
    image: docker.elastic.co/logstash/logstash:6.0.1
    command: -f /etc/logstash/conf.d/
    volumes:
      - ./logstash/:/etc/logstash/conf.d/
    ports:
      - "5000:5000"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
